"""Blocos fixos do .e2k copiados de um arquivo gravado pelo ETABS 23.3.1 (MARAMBAIA-V40Design.e2k),
que importa corretamente. Mantem-se a ordem completa de secoes do ETABS; secoes vazias ficam so
com o cabecalho. Separador decimal aqui e virgula (o do arquivo de origem); o escritor troca
quando a configuracao pedir ponto.
"""

# Ordem completa das secoes gravadas pelo ETABS 23.x
SECTION_ORDER = [
    "PROGRAM INFORMATION", "CONTROLS", "STORIES - IN SEQUENCE FROM TOP", "GRIDS", "DIAPHRAGM NAMES",
    "MATERIAL PROPERTIES", "REBAR DEFINITIONS", "FRAME SECTIONS", "CONCRETE SECTIONS", "TENDON SECTIONS",
    "SLAB PROPERTIES", "DECK PROPERTIES", "WALL PROPERTIES", "LINK PROPERTIES", "PANEL ZONE PROPERTIES",
    "POINT SPRING PROPERTIES", "PIER/SPANDREL NAMES ", "POINT COORDINATES", "LINE CONNECTIVITIES",
    "AREA CONNECTIVITIES", "GROUPS", "POINT ASSIGNS", "LINE ASSIGNS", "AREA ASSIGNS", "FUNCTIONS",
    "LOAD PATTERNS", "POINT OBJECT LOADS", "FRAME OBJECT LOADS", "SHELL UNIFORM LOAD SETS",
    "SHELL OBJECT LOADS", "ANALYSIS OPTIONS", "MASS SOURCE", "GENERALIZED DISPLACEMENTS", "LOAD CASES",
    "LOAD COMBINATIONS", "STEEL DESIGN PREFERENCES", "CONCRETE DESIGN PREFERENCES",
    "COMPOSITE DESIGN PREFERENCES", "COMPOSITE COLUMN DESIGN PREFERENCES", "WALL DESIGN PREFERENCES",
    "CONCRETE SLAB DESIGN PREFERENCES", "CONCRETE SHELL DESIGN PREFERENCES", "DIMENSION LINES",
    "DEVELOPED ELEVATIONS", "TABLE SETS", "PROJECT INFORMATION", "LOG",
]

STEEL_MATERIAL = """\
  MATERIAL  "STEEL"    TYPE "Steel"    WEIGHTPERVOLUME 76,81955
  MATERIAL  "STEEL"    SYMTYPE "Isotropic"  E 199948000  U 0,3  A 1,1699999959091656E-05
  MATERIAL  "STEEL"  FY 344737,9  FU 448159,3 FYE 379211,7  FUE 492975,2
  MATERIAL  "STEEL"  HYSTYPE "Kinematic"  SSTYPE "Simple"  STRAINATHARDENING 0,015 STRAINATMAXSTRESS 0,11 STRAINATRUPTURE 0,17 FINALSLOPE -0,1 IOTENSION 0,01 LSTENSION 0,02 CPTENSION 0,05 IOCOMPRESSION 0,005 LSCOMPRESSION 0,01 CPCOMPRESSION 0,02 """

REBAR_MATERIAL = """\
  MATERIAL  "A615Gr60"    TYPE "Rebar"    WEIGHTPERVOLUME 76,97286
  MATERIAL  "A615Gr60"    SYMTYPE "Uniaxial"  E 199948000  A 1,1699999959091656E-05
  MATERIAL  "A615Gr60"  FY 413685,5  FU 620528,2 FYE 455054  FUE 682581
  MATERIAL  "A615Gr60"  HYSTYPE "Kinematic"  SSTYPE "Simple"  STRAINATHARDENING 0,01 STRAINATULTIMATE 0,09 FINALSLOPE -0,1 IOTENSION 0,01 LSTENSION 0,02 CPTENSION 0,05 IOCOMPRESSION 0,005 LSCOMPRESSION 0,01 CPCOMPRESSION 0,02 """

# {name}, {weight}, {e}, {fc} preenchidos pelo escritor (numeros ja formatados)
CONCRETE_MATERIAL = """\
  MATERIAL  "{name}"    TYPE "Concrete"    WEIGHTPERVOLUME {weight}
  MATERIAL  "{name}"    SYMTYPE "Isotropic"  E {e}  U 0,2  A 9,899999895424116E-06
  MATERIAL  "{name}"    FC {fc}
  MATERIAL  "{name}"  TIMEDEPCONCCODE "CEBFIP90"
  MATERIAL  "{name}"  HYSTYPE "Concrete"  ENERGYDEGFACT 0 SSTYPE "Simple"  STRAINATFC 0,00221914 STRAINATULTIMATE 0,005 FINALSLOPE -0,1 IOTENSION 0,01 LSTENSION 0,02 CPTENSION 0,05 IOCOMPRESSION 0,003 LSCOMPRESSION 0,006 CPCOMPRESSION 0,015 """

REBAR_DEFINITIONS = """\
  REBARDEFINITION  "#3"  AREA  7,09676E-05 DIA  0,009525
  REBARDEFINITION  "#4"  AREA  0,000129032 DIA  0,0127
  REBARDEFINITION  "#5"  AREA  0,0001999996 DIA  0,015875
  REBARDEFINITION  "#6"  AREA  0,0002838704 DIA  0,01905
  REBARDEFINITION  "#8"  AREA  0,0005096764 DIA  0,0254
  REBARDEFINITION  "6d"  AREA  2,83E-05 DIA  0,006
  REBARDEFINITION  "8d"  AREA  5,03E-05 DIA  0,008
  REBARDEFINITION  "10d"  AREA  7,85E-05 DIA  0,01
  REBARDEFINITION  "12d"  AREA  0,000113 DIA  0,012
  REBARDEFINITION  "16d"  AREA  0,000201 DIA  0,016
  REBARDEFINITION  "20d"  AREA  0,000314 DIA  0,02
  REBARDEFINITION  "25d"  AREA  0,000491 DIA  0,025 """

CONCRETE_SECTION_BEAM = ('  CONCRETESECTION  "{name}"  LONGBARMATERIAL "A615Gr60"  CONFINEBARMATERIAL "A615Gr60"  '
                         'TYPE "Beam"  COVERTOP 0,04 COVERBOTTOM 0,04 ATI 0 ABI 0 ATJ 0 ABJ 0 ')
CONCRETE_SECTION_COLUMN = ('  CONCRETESECTION  "{name}"  LONGBARMATERIAL "A615Gr60"  CONFINEBARMATERIAL "A615Gr60"  '
                           'TYPE "Column"  PATTERN "R-5-3"  TRANSREINF "TIES"  DESIGNCHECK "DESIGN"  COVER 0,04 '
                           'LONGBARAREA 3,2258E-05 CONFINEBARAREA 3,2258E-05 CONFINEBARSPACING 0,15 '
                           'NUMCONFINEBARS3 3 NUMCONFINEBARS2 3 ')

DESIGN_PREFERENCES = {
    "STEEL DESIGN PREFERENCES": """\
  STEELPREFERENCE  CODE "AISC 360-10"  THDESIGN "EVERYSTEP"  FRAMETYPE "SMF"
  STEELPREFERENCE  SDC "D"  IMPORTANCEFACTOR 1 SYSTEMRHO 0 SYSTEMSDS 1
  STEELPREFERENCE  SYSTEMR 8 OMEGA0 3 SYSTEMCD 5,5
  STEELPREFERENCE  PROVISION "LRFD"  ANALYSISMETHOD "DIRECT ANALYSIS"  SECONDORDERMETHOD "GENERAL 2ND ORDER"  STIFFNESSREDUCTIONMETHOD "TAU-B FIXED"  AANOTIONALTOLATERALCOMBOS "NO"  BETA 1,3 BETAOMEGA 1,6
  STEELPREFERENCE  PHIBAISC05 0,9 PHICAISC05 0,9 PHITYAISC05 0,9 PHITFAISC05 0,75
  STEELPREFERENCE  PHIVAISC05 0,9 PHIVROLLEDIAISC05 1 PHITORSIONAISC05 0,9
  STEELPREFERENCE  IGNORESEISMICCODE "NO"  IGNORESPECIALSEISMICLOAD "NO"  ISDOUBLERPLATEPLUGWELDED "YES"
  STEELPREFERENCE  HSSWELDINGTYPE "ERW"   REDUCEHSSTHICKNESS "NO"
  STEELPREFERENCE  CONSIDERDEFLECTION "YES"
  STEELPREFERENCE  DLDEFLECTIONLIMIT 120 SLDEFLECTIONLIMIT 120 LLDEFLECTIONLIMIT 360 TLDEFLECTIONLIMIT 240 TLMCDEFLECTIONLIMIT 240
  STEELPREFERENCE  PATTERNLLF 0,75 MAXITERATION 1 SRLIMIT 0,95 """,
    "CONCRETE DESIGN PREFERENCES": """\
  CONCRETEPREFERENCE  CODE "ACI 318-08" THDESIGN "EVERYSTEP"    CONSIDERMINECCENTRICITY "YES"    DESIGNFORBCCR "YES"    IGNOREBENEFICIALPUINBEAMDESIGN "NO"
  CONCRETEPREFERENCE  NUMINTERCURVES 24  NUMINTERPOINTS 11  PATTERNLLF 0,75  UFLIMIT 0,95
  CONCRETEPREFERENCE  SDC "D"    RHO 1  SDS 1
  CONCRETEPREFERENCE  PHITENSIONCTRL 0,9  PHICOMPRESSIONCTRLTIED 0,65  PHICOMPRESSIONCTRLSPIRAL 0,7
  CONCRETEPREFERENCE  PHISHEARTORSION 0,75  PHISHEARSEISMIC 0,6  PHISHEARJOINT 0,85
  CONCRETEPREFERENCE  USERSTRESS "NO"  INITCONCRAT 0,8  LLFRACTION 0,5""",
    "COMPOSITE DESIGN PREFERENCES": """\
  COMPOSITEPREFERENCE  CODE "AISC 360-05"
  COMPOSITEPREFERENCE  PHI-B 0,9  PHI-BCNE 0,9  PHI-BCNP 0,9  PHI-BCPP 0,85  PHI-V 0,9  PHI-C 0,9  PHI-T 0,9
  COMPOSITEPREFERENCE  SHORED "NO"   WITHAXIALFORCE  "NO"    %MIDDLERANGE 70  SRLIMIT 1
  COMPOSITEPREFERENCE  MIN%COMPOSITE 25  MAX%COMPOSITE 100  SINGLESEGMENT "NO"
  COMPOSITEPREFERENCE  MINLONGSPACING 0,1143  MAXLONGSPACING 0,9144  MINTRANSSPACING 0,0762  MAXSTUDSPERROW 3
  COMPOSITEPREFERENCE  DLLIMIT 0  SLLIMIT 240  LLLIMIT 360  TLLIMIT 240  CREEPFACTOR 1
  COMPOSITEPREFERENCE  CALCULATECAMBER "YES"    %DLCAMBER 100  MINDEPTHFORCAMBER 0,3429  MINWEBTHICKFORCAMBER 0,00635  MINSPANFORCAMBER 7,3152
  COMPOSITEPREFERENCE  CAMBERIGNORE 0,01905  CAMBERELMIN 900  CAMBERABSMAX 0,1016  CAMBERRELMAX 180  CAMBERINTERVAL 0,006349999  CAMBERROUNDDOWN "YES"
  COMPOSITEPREFERENCE  %VIBLL 25  CONSIDERFREQ "NO"    MINFREQ 8  CONSIDERDAMP "NO"    %INHERENTDAMP 4
  COMPOSITEPREFERENCE  VIBRATIONCRITERION "WALKING"  OCCUPANCYCATEGORY "PAPEROFFICE"  DAMPINGRATIO 0,025  P065  Q168  WALKINGACCELERATIONLIMIT 0,005
  COMPOSITEPREFERENCE  RHYTHMICACTIVITY "AEROBICS"  AFFECTEDOCCUPANCYCATEGORY "PAPEROFFICE"
  COMPOSITEPREFERENCE  RHYTHMICACCELERATIONLIMIT 0,005  UPPERSTEPFREQUENCY 2,75  LOWERSTEPFREQUENCY 2  NUMBERFREQUENCIES 16
  COMPOSITEPREFERENCE  EQUIPMENTORUSECATEGORY "COMPUTERSYSTEM"  VIBVELOCITYLIMIT 2438,4  WALKINGSPEED "VERYSLOW"
  COMPOSITEPREFERENCE  SENSITIVIBFSTEP 1,25  SENSVIBFL 6  SENSVIBFU 8  SENSVIBGAMMA  0,1
  COMPOSITEPREFERENCE  OPTIMIZEPRICE "NO"    STEELPRICE 0,2248089  CONNECTORPRICE 0  CAMBERPRICE 0""",
    "COMPOSITE COLUMN DESIGN PREFERENCES": """\
  COMPOSITECOLUMNPREFERENCE  CODE "AISC 360-10"  THDESIGN "EVERYSTEP-ALL"
  COMPOSITECOLUMNPREFERENCE  PROVISION "LRFD"  ANALYSISMETHOD "DIRECT ANALYSIS"  SECONDORDERMETHOD "GENERAL 2ND ORDER"  STIFFNESSREDUCTIONMETHOD "TAU-B FIXED"
  COMPOSITECOLUMNPREFERENCE  PHIBAISC05 0,9 PHICAISC05 0,75 PHITYAISC05 0,9 PHITFAISC05 0,75
  COMPOSITECOLUMNPREFERENCE  PHIVAISC05 0,9 PHIVROLLEDIAISC05 1 PHIVREINFCOMPOSITEAISC22 0,75 PHITORSIONAISC05 0,9
  COMPOSITECOLUMNPREFERENCE  PHICSAS1619 0,9 PHIUCSAS1619 0,75 PHICCSAS1619 0,65 PHIRCSAS1619 0,85
  COMPOSITECOLUMNPREFERENCE  IGNORESEISMICCODE "NO"  IGNORESPECIALSEISMICLOAD "NO"  ISDOUBLERPLATEPLUGWELDED "YES"
  COMPOSITECOLUMNPREFERENCE  HSSWELDINGTYPE "ERW"   REDUCEHSSTHICKNESS "NO"
  COMPOSITECOLUMNPREFERENCE  PATTERNLLF 0,75 MAXITERATION 1 SRLIMIT 0,95 """,
    "WALL DESIGN PREFERENCES": """\
  WALLPREFERENCE  CODE "Eurocode 2-2004"  THDESIGN "EVERYSTEP-ALL"
  WALLPREFERENCE  REBARMATERIAL "A615Gr60"  REBARSHEARMATERIAL "A615Gr60"
  WALLPREFERENCE  COUNTRY "CEN_DEFAULT"    COMBOSFROM "EQ6.10"  RELCLAS "CLASS_2"    SECONDORDERMETHOD "NOMINAL_STIFFNESS"    CONSIDERMINECCENTRICITY "YES"
  WALLPREFERENCE  EUROTHETA004 0,005  SHEARMF 2  DUCTILITYSF 2  EUROGAMMAS04 1,15  EUROGAMMAC04 1,5
  WALLPREFERENCE  EUROALPHACC04 1  EUROALPHACT04 1  EUROALPHALCC04 0,85  EUROALPHALCT04 0,85
  WALLPREFERENCE  NUMCURVES 24  NUMPOINTS 11
  WALLPREFERENCE  PTMAX 0,06  PCMAX 0,04  IPMAX 0,04  IPMIN 0,0025
  WALLPREFERENCE  UFLIMIT 0,95""",
    "CONCRETE SLAB DESIGN PREFERENCES": """\
  CONCRETESLABPREFERENCE  CODE "ACI 318-14"  PHITENACI 0,9  PHICOMPACI 0,65  PHISHEARACI 0,75
  CONCRETESLABPREFERENCE  IGNOREBENEFICIALPUINSLABDESIGN "YES"    PATTERNLLF 0,75
  CONCRETESLABPREFERENCE  COVERTOP 0,01905  COVERBOT 0,01905  BARSIZE "#6"  INNERLAYER "B"    PTCGSTOP 0,0254  PTCGSBOTEXT 0,04445  PTCGSBOTINT 0,0254  SLABTYPE "Two Way"
  CONCRETESLABPREFERENCE  USERSTRESS "No"  INITCONCRAT 0,8  LLFRACTION 0,5""",
    "CONCRETE SHELL DESIGN PREFERENCES": """\
  CONCRETESHELLPREFERENCE  PATTERNLLF 0,75  UFLIMIT 1
  CONCRETESHELLPREFERENCE  COUNTRY "CEN_DEFAULT"    COMBOSFROM "EQ6.10"    RELCLASS "CLASS_2"
  CONCRETESHELLPREFERENCE  EUROGAMMAS04 1,15  EUROGAMMAC04 1,5
  CONCRETESHELLPREFERENCE  EUROALPHACC04 1  EUROALPHACT04 1
  CONCRETESHELLPREFERENCE CRACKCONDITION "PROGRAMDETERMINED"   SHEARDESIGNMETHOD "METHOD1"    COTTHETA 1  ADDTENSILEFORCEDUETOSHEAR "YES"
  CONCRETESHELLPREFERENCE  CONSIDERSHEARDESIGN "YES"  """,
}

MASS_SOURCE_HEADER = ('  MASSSOURCE  "MsSrc1"    INCLUDEELEMENTS "No"    INCLUDEADDEDMASS "No"    INCLUDELOADS "Yes"    '
                      'INCLUDEMOVE "No"    INCLUDELATERALMASS "Yes"    INCLUDEVERTICALMASS "No"    LUMPATSTORIES "Yes"    '
                      'ISDEFAULT "Yes"  ')
